host: localhost
port: 8778
config_directory: /Users/dimi5963/projects/repose/repose-aggregator/functional-tests/spock-functional-test/target/repose_home/configs
output_directory: /Users/dimi5963/projects/repose/repose-aggregator/functional-tests/spock-functional-test/target/repose_home/configs
