source 'https://rubygems.org'
gem 'rspec', '~>2.14.1'
gem 'sinatra', '~>1.4.3'
gem 'logging'
gem 'rest_client'
gem 'rspec-mocks'
gem 'simplecov-rcov'
gem 'simplecov'
gem 'ci_reporter'
gem 'nokogiri'
group :development do
  gem 'guard'
  gem 'guard-livereload', '~> 2.1.2'
  gem 'guard-rspec', '~> 4.2.8'
  gem 'guard-cucumber', '~> 1.4.1'
  gem 'guard-jasmine', '~> 1.19.2'
  gem 'growl'
  gem 'simplecov'
  gem 'watchr'
  gem 'rev'
  gem 'autowatchr'
  gem 'cucumber'
  gem 'cucumber-sinatra','~>0.5.0', :require => 'cucumber'
  gem 'capybara'
end
