# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty-server-cloudimg-amd64"

  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 9292, host: 8081
  config.vm.synced_folder "repose", "/usr/share/repose", create: true
  config.vm.synced_folder "configs", "/etc/repose", create: true
  config.vm.synced_folder "../", "/usr/share/coverage", create: true
  config.vm.provision :shell, inline: 'sudo /usr/share/coverage/vagrant/setup_vm.sh'
end
